/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org/rsmaster.app

import org/rsmaster.utilities.StringUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    println(StringUtils.join(tokens))
}
